title: Ken Tucker's Blog
email: csharp2ae@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Adventures in programming in c# and VB.net for the .net framework and .net core.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vb2ae
github_username:  vb2ae

# Build settings
theme: minima
